//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonorAppVersion2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonorsRegisteredWithPartner
    {
        public int DonorPartnerId { get; set; }
        public int DonorId { get; set; }
        public int PartnerContactsId { get; set; }
        public bool isApproved { get; set; }
        public Nullable<System.DateTime> DateOfApproval { get; set; }
        public string Status { get; set; }
        public string DonorIdOnPartnerSystem { get; set; }
    
        public virtual Donor Donor { get; set; }
        public virtual PartnerAndTheirContact PartnerAndTheirContact { get; set; }
    }
}
