
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DonorAppVersion2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DonorAilmentDetail
{

    public int DonorAilmentId { get; set; }

    public int DonorId { get; set; }

    public string TypeOfAilment { get; set; }

    public string SystemInBodyAffected { get; set; }

    public string BodyPart { get; set; }



    public virtual Donor Donor { get; set; }

}

}
