//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonorAppVersion2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class DonorCycle
    {
        public DonorCycle()
        {
            this.DonorCycleUpdates = new HashSet<DonorCycleUpdate>();
            this.PartnersAttachedToDonorCycles = new HashSet<PartnersAttachedToDonorCycle>();
        }
    
        public int DonorCycleId { get; set; }
        public int ParentId { get; set; }

        [Display(Name="Donors Unique Donor21 Donor ID")]
        public int DonorId { get; set; }

        [Display(Name = "Month and Year of Retrieval")]
        public string MonthAndYearOfRetrieval { get; set; }

        [Display(Name = "Fertility Attorny")]
        public string FertilityAttorny { get; set; }

        [Display(Name = "Donor Eye Color")]
        public string DonorEyeColor { get; set; }

        [Display(Name = "Donor Height")]
        public string DonorHeight { get; set; }

        [Display(Name = "Donor Age")]
        public string DonorAge { get; set; }


        public Nullable<bool> isApprovedByParent { get; set; }
        public Nullable<bool> isApprovedByDonor { get; set; }
        public Nullable<bool> isApprovedByClinic { get; set; }
        public Nullable<bool> isApprovedByAgency { get; set; }
    
        public virtual Donor Donor { get; set; }
        public virtual Parent Parent { get; set; }
        public virtual ICollection<DonorCycleUpdate> DonorCycleUpdates { get; set; }
        public virtual ICollection<PartnersAttachedToDonorCycle> PartnersAttachedToDonorCycles { get; set; }
    }
}
