//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonorAppVersion2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonorCycleUpdate
    {
        public int DonorCycleUpdateId { get; set; }
        public int DonorCycleId { get; set; }
        public string UpdateHeading { get; set; }
        public string UpdateDescription { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public bool isSubmitted { get; set; }
        public bool isCompleted { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
    
        public virtual DonorCycle DonorCycle { get; set; }
    }
}
