
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DonorAppVersion2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DonorCycle
{

    public DonorCycle()
    {

        this.DonorCycleUpdates = new HashSet<DonorCycleUpdate>();

        this.PartnersAttachedToDonorCycles = new HashSet<PartnersAttachedToDonorCycle>();

    }


    public int DonorCycleId { get; set; }

    public int ParentId { get; set; }

    public int DonorId { get; set; }

    public string MonthAndYearOfRetrieval { get; set; }

    public string FertilityAttorny { get; set; }

    public string DonorEyeColor { get; set; }

    public string DonorHeight { get; set; }

    public string DonorAge { get; set; }

    public Nullable<bool> isApprovedByParent { get; set; }

    public Nullable<bool> isApprovedByDonor { get; set; }

    public Nullable<bool> isApprovedByClinic { get; set; }

    public Nullable<bool> isApprovedByAgency { get; set; }



    public virtual Donor Donor { get; set; }

    public virtual Parent Parent { get; set; }

    public virtual ICollection<DonorCycleUpdate> DonorCycleUpdates { get; set; }

    public virtual ICollection<PartnersAttachedToDonorCycle> PartnersAttachedToDonorCycles { get; set; }

}

}
