//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonorAppVersion2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyOfIntendedParent
    {
        public int IntendedFamilyId { get; set; }
        public int PrimaryParentId { get; set; }
        public int IntendedParentId { get; set; }
        public string Relation { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool isVerified { get; set; }
        public string Status { get; set; }
    
        public virtual Parent Parent { get; set; }
        public virtual Parent Parent1 { get; set; }
    }
}
