
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DonorAppVersion2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class FamilyDiseaseQuestion
{

    public FamilyDiseaseQuestion()
    {

        this.DonorFamilyTreeDiseaseDetails = new HashSet<DonorFamilyTreeDiseaseDetail>();

        this.ParentFamilyTreeDiseaseDetails = new HashSet<ParentFamilyTreeDiseaseDetail>();

    }


    public int FamilyDiseaseQuestionId { get; set; }

    public string Question { get; set; }



    public virtual ICollection<DonorFamilyTreeDiseaseDetail> DonorFamilyTreeDiseaseDetails { get; set; }

    public virtual ICollection<ParentFamilyTreeDiseaseDetail> ParentFamilyTreeDiseaseDetails { get; set; }

}

}
