//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonorAppVersion2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthQuestion
    {
        public HealthQuestion()
        {
            this.DonorHealthQuestionsAnswereds = new HashSet<DonorHealthQuestionsAnswered>();
            this.ParentsHealthQuestionsAnswereds = new HashSet<ParentsHealthQuestionsAnswered>();
        }
    
        public int HealthQuestionId { get; set; }
        public string HealthQuestion1 { get; set; }
        public string Options { get; set; }
    
        public virtual ICollection<DonorHealthQuestionsAnswered> DonorHealthQuestionsAnswereds { get; set; }
        public virtual ICollection<ParentsHealthQuestionsAnswered> ParentsHealthQuestionsAnswereds { get; set; }
    }
}
