//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonorAppVersion2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchDetail
    {
        public int MatchId { get; set; }
        public int ParentId { get; set; }
        public int DonorId { get; set; }
        public Nullable<bool> isApprovedByParent { get; set; }
        public Nullable<bool> isApprovedByDonor { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateOfCompletion { get; set; }
    
        public virtual Donor Donor { get; set; }
        public virtual Parent Parent { get; set; }
    }
}
