//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonorAppVersion2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParentAilmentDetail
    {
        public int ParentAilmentId { get; set; }
        public int ParentId { get; set; }
        public string TypeOfAilment { get; set; }
        public string SystemInBodyAffected { get; set; }
        public string BodyPart { get; set; }
    
        public virtual Parent Parent { get; set; }
    }
}
