
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DonorAppVersion2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ParentFamilyTreeDiseaseDetail
{

    public int ParentFamilyDiseaseTreeId { get; set; }

    public int ParentId { get; set; }

    public int FamilyTreeDiseaseId { get; set; }

    public int FamilyDiseaseQuestionId { get; set; }

    public string Answer { get; set; }



    public virtual FamilyDiseaseQuestion FamilyDiseaseQuestion { get; set; }

    public virtual FamilyTreeDiseaseDetail FamilyTreeDiseaseDetail { get; set; }

    public virtual Parent Parent { get; set; }

}

}
