//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonorAppVersion2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParentsRegisteredWithPartner
    {
        public int ParentPartnerId { get; set; }
        public int ParentId { get; set; }
        public int PartnerContactsId { get; set; }
        public bool isApproved { get; set; }
        public Nullable<bool> DateOfApproval { get; set; }
        public string Status { get; set; }
        public string ParentIdOnPartnersSystem { get; set; }
    
        public virtual Parent Parent { get; set; }
        public virtual PartnerAndTheirContact PartnerAndTheirContact { get; set; }
        public virtual Partner Partner { get; set; }
    }
}
