
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DonorAppVersion2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Partner
{

    public Partner()
    {

        this.ParentsRegisteredWithPartners = new HashSet<ParentsRegisteredWithPartner>();

        this.PartnerAndTheirContacts = new HashSet<PartnerAndTheirContact>();

    }


    public int PartnerId { get; set; }

    public string AssociationType { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public string State { get; set; }

    public string Zip { get; set; }

    public string BusinessContact { get; set; }

    public string BusinessWebsite { get; set; }

    public string BusinessEmail { get; set; }

    public string ContactPersonName { get; set; }

    public string ContactPersonContact { get; set; }

    public string ContactPersonEmail { get; set; }

    public string Password { get; set; }

    public string Salt { get; set; }

    public System.DateTime CreationDate { get; set; }



    public virtual ICollection<ParentsRegisteredWithPartner> ParentsRegisteredWithPartners { get; set; }

    public virtual ICollection<PartnerAndTheirContact> PartnerAndTheirContacts { get; set; }

}

}
