//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonorAppVersion2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnersAttachedToDonorCycle
    {
        public int DonorCyclePartnersId { get; set; }
        public int DonorCycleId { get; set; }
        public int PartnerContactsId { get; set; }
        public bool isApprovedByPartner { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateOfApproval { get; set; }
    
        public virtual DonorCycle DonorCycle { get; set; }
        public virtual PartnerAndTheirContact PartnerAndTheirContact { get; set; }
    }
}
