//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonorAppVersion2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerAndTheirContact
    {
        public PartnerAndTheirContact()
        {
            this.DonorsRegisteredWithPartners = new HashSet<DonorsRegisteredWithPartner>();
            this.ParentsRegisteredWithPartners = new HashSet<ParentsRegisteredWithPartner>();
            this.PartnersAttachedToDonorCycles = new HashSet<PartnersAttachedToDonorCycle>();
        }
    
        public int PartnerContactsId { get; set; }
        public int PartnerId { get; set; }
        public string ContactDesignation { get; set; }
        public string ContactName { get; set; }
        public string ContactEmail { get; set; }
        public string ContactPhone { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual ICollection<DonorsRegisteredWithPartner> DonorsRegisteredWithPartners { get; set; }
        public virtual ICollection<ParentsRegisteredWithPartner> ParentsRegisteredWithPartners { get; set; }
        public virtual Partner Partner { get; set; }
        public virtual ICollection<PartnersAttachedToDonorCycle> PartnersAttachedToDonorCycles { get; set; }
    }
}
