
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DonorAppVersion2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PaymentSummuryParent
{

    public int ParentsPaymentId { get; set; }

    public int ParentId { get; set; }

    public double Amount { get; set; }

    public string PaymentFor { get; set; }

    public string PaymentDescription { get; set; }

    public bool PaymentStatus { get; set; }

    public string TransactionReferenceNumber { get; set; }

    public Nullable<bool> isDue { get; set; }

    public Nullable<System.DateTime> DueDate { get; set; }

    public string Note { get; set; }



    public virtual Parent Parent { get; set; }

}

}
